-- 1️⃣ Find the 2nd highest salary (without using LIMIT / TOP)
-- Table: employees(emp_id, name, salary)
-- 👉 Write a query to get the 2nd highest salary in the company.

CREATE DATABASE COMPANY;
USE COMPANY;

CREATE TABLE EMPLOYEES(
emp_id INT PRIMARY KEY,
name VARCHAR(20),
salary DOUBLE NOT NULL
);

INSERT INTO EMPLOYEES VALUES (101,"Nora", 50000.0);
INSERT INTO EMPLOYEES VALUES (102,"Ashu", 40000.0);
INSERT INTO EMPLOYEES VALUES (103,"Arra", 70000.0);
INSERT INTO EMPLOYEES VALUES (104,"Arraha", 80000.0);
INSERT INTO EMPLOYEES VALUES (105,"Menna", 90000.0);
INSERT INTO EMPLOYEES VALUES (106,"Abhi", 50000.0);
INSERT INTO EMPLOYEES VALUES (107,"Chandu", 30000.0);
INSERT INTO EMPLOYEES VALUES (108,"Faraha", 32000.0);
INSERT INTO EMPLOYEES VALUES (109,"Epsiba", 29000.0);
INSERT INTO EMPLOYEES VALUES (110,"Rena", 100000.0);

SELECT * FROM EMPLOYEES; 

SELECT MAX(salary) AS second_Highest_salary
FROM EMPLOYEES
WHERE salary <(SELECT MAX(salary) FROM EMPLOYEES);
